language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.1.300

services:
  - postgresql
addons:
  postgresql: "9.6"

env:
  global:
    - NPGSQL_TEST_DB: '"Host=localhost;Port=5433;Database=npgsql_tests;Username=npgsql_tests;Password=npgsql_tests"'
    - PGPORT: 5433

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis'"  # For PG 10 hack
  - psql -c "CREATE USER npgsql_tests PASSWORD 'npgsql_tests' SUPERUSER"
  - psql -c "CREATE DATABASE npgsql_tests OWNER npgsql_tests"
  - psql -c "CREATE EXTENSION citext" npgsql_tests
  - psql -c "CREATE EXTENSION postgis" npgsql_tests
  - dotnet restore -v Minimal Npgsql.sln
script:
  - dotnet build "test/Npgsql.Tests" -c Debug -f netcoreapp2.1
  - dotnet build "test/Npgsql.PluginTests" -c Debug -f netcoreapp2.1
  - dotnet test "test/Npgsql.Tests/Npgsql.Tests.csproj" -c Debug -f netcoreapp2.1
  - dotnet test "test/Npgsql.PluginTests/Npgsql.PluginTests.csproj" -c Debug -f netcoreapp2.1

cache:
  directories:
    - $HOME/.nuget/packages

# The following is necessary because of https://github.com/travis-ci/travis-ci/issues/6972
addons:
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4
    - postgresql-10-postgis-2.4-scripts
  postgresql: 10
